#Build commands for building docker Image from source repo Dockerfile..
version: 0.2
phases:
  #Phase for logging into docker through aws using ECR repository uri, creating unique tag
  pre_build:
    commands:
      - echo $projectid $Branch revision ...
      - export UNIQUE_TAG=$(date +%Y%m%d%H%M%S)
      - COMMIT_MESSAGE=$(git log --format=%B -n 1 $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - echo "Commit message-> $COMMIT_MESSAGE"                              
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info > /dev/null 2>&1; do sleep 1; done"
  #Conditional block 
  build:
    commands:
      - |
        if [[ ! "$COMMIT_MESSAGE" == *"builder update"* ]]; then
          ###APP CODE REVISION BLOCK
          echo "Starting code base update flow..."
          export NEW_IMAGE_URI="$Ecr/$EcrRepoName:CodeBase$UNIQUE_TAG"
          export BUILD_LOCATION="api-services/src"
          docker-build.sh
          update-lambda-uri.sh
          TEST_RESULT=$(test-request.py)
          promote-to-live.py $TEST_RESULT
        else
          ###BUILDER AMI CODE REVISION BLOCK
          echo "Starting cicd builder AMI update flow..."
          export NEW_IMAGE_URI="$Ecr/$EcrRepoName:Builder$UNIQUE_TAG"
          export BUILD_LOCATION="cicd-image"
          docker-build.sh
          update-build-ami.py 
          echo "Done."
        fi