#Build commands for building docker image from source repo Dockerfile..
version: 0.2
phases:
  pre_build:
    #phase for logging into docker through aws using ECR repo uri, creating image id and locally caching python.
    commands:
      - echo Beginning build phase for new $Branch update ...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $Ecr
      - export uniquetag=$(date +%Y%m%d%H%M%S)
      - echo initializing python locally to create docker image
      - cd src
      - ls
  build:
    #phase for building and pushing image to ECR
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo Building the Docker image for repo $EcrRepoName...
      - docker build -t $EcrRepoName:$uniquetag .
      - echo Tagging and Pushing the Docker image to Amazon ECR...
      - docker tag $EcrRepoName:$uniquetag $Ecr/$EcrRepoName:$uniquetag
      - docker push $Ecr/$EcrRepoName:$uniquetag
        
  post_build:
    #update lambda microservice 
    commands:
      - echo Updating the Lambda function code to use the new $Branch Docker image...
      - aws lambda update-function-code --function-name MainLambdaMS$Branch$projectid --image-uri $Ecr/$EcrRepoName:$uniquetag --publish