version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "microservicestackprod7070"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nx60q3ga33u0"
s3_prefix = "microservicestackprod7070"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "projectid=\"7070\" initialimageuri=\"223634373127.dkr.ecr.us-east-1.amazonaws.com/nfttest:20230727215934\" sourcebranch=\"prod\""
image_repositories = []
